version: "3"
services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/production/Dockerfile
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
      DOMAIN: ${DOMAIN}
    ports: 
      - 80:80
      - 443:443
    networks:
      - internal
    volumes:
      - ./nginx/templates:/etc/nginx/templates/
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # This should be your own web domain and email address
    command: certonly --webroot --webroot-path /var/www/certbot/ --email ${EMAIL} -d ${DOMAIN} --agree-tos --no-redirect  --non-interactive
  php:
    restart: always
    build:
      context: .
      dockerfile: php/Dockerfile-production
    environment:
      API_KEY: ${API_KEY}
    networks:
      - internal
networks:
  internal:
    driver: bridge