version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - 80:80
      - 443:443
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes: 
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    # This should be your own web domain and email address
    command: certonly --webroot -w /var/www/certbot --force-renewal --email corbindavenport@outlook.com -d corbintesting.com --agree-tos --no-redirect  --non-interactive --dry-run
  php:
    image: php:fpm-alpine
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./data/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
networks:
  internal:
    driver: bridge